steps:
  - block: "Build :debian:?"
    # The block step will only exist if the conditions below are true
    # Block only when triggered from kolibri pipeline and is not a release
    if: build.env("LE_KOLIBRI_RELEASE") == "false"
  - label: ":debian:"
    command: .buildkite/build.sh

  - wait

  - label: Test ubuntu:focal
    env:
      DOCKER_IMAGES: ubuntu:focal
    command: .buildkite/test.sh
    
  - label: Test ubuntu:bionic
    env:
      DOCKER_IMAGES: ubuntu:bionic
    command: .buildkite/test.sh
  - label: Test ubuntu:xenial
    env:
      DOCKER_IMAGES: ubuntu:xenial
    command: .buildkite/test.sh
  - label: Test ubuntu:trusty
    env:
      DOCKER_IMAGES: ubuntu:trusty
    command: .buildkite/test.sh
